// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oftnisnqpopthncdkdgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mdG5pc25xcG9wdGhuY2RrZGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMzg5MDEsImV4cCI6MjA4NzcxNDkwMX0.v1avy2KZjGK3dVFx0ZCc_IlLBDkSdyYE2lAWOtaZvT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});